const FETCH_START_TOP_TRACKS = 'TRACKS/FETCH_TOP_START';
const FETCH_END_TOP_TRACKS = 'TRACKS/FETCH_TOP_END';
const SELECT_TOP_TRUCK = 'TRACKS/SELECT_TOP';
const DESELECT_TOP_TRUCK = 'TRACKS/DESELECT_TOP';
const FETCH_START_RECOMMEND_TRACKS = 'TRACKS/FETCH_RECOMMEND_START';
const FETCH_END_RECOMMEND_TRACKS = 'TRACKS/FETCH_RECOMMEND_END';

export default {
    FETCH_START_TOP_TRACKS,
    FETCH_END_TOP_TRACKS,
    SELECT_TOP_TRUCK,
    DESELECT_TOP_TRUCK,
    FETCH_START_RECOMMEND_TRACKS,
    FETCH_END_RECOMMEND_TRACKS
};
